{% set version = "1.6.1" %}

package:
  name: crystals
  version: {{ version }}

source:
  fn: crystals-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/crystals/crystals-{{ version }}.tar.gz
  sha256: 6f22d3b5a46b987c79ea16664ab6f722325f3d9ebc3fc24a089e7c09e086ee9e

build:
  noarch: python
  number: 1
  entry_points:
    - crystals = crystals.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7 # requires pathlib
    - pip
  run:
    - python >=3.7
    - numpy >=1.17, <2
    - spglib >=1.15, <3
    - pycifrw >=4.4.1, <5
    - requests >=2, <3

test:
  imports:
    - crystals
  commands:
    - crystals --help
    # crystals does not use pytest to run tests, it uses unittest.
    # However, the discovery of tests by unittest is lacking when packages are
    # installed. Since pytest supports running unittest tests, we use it instead.
    - pytest --pyargs crystals
  requires:
    - pytest

about:
  home: https://crystals.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Data structures for crystallography
  description: |
    crystals provides data structure to manipulate crystal structures, including parsing 
    crystal files, determining symmetries, and accessing atomic information.
  doc_url: https://crystals.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/crystals

extra:
  recipe-maintainers:
    - LaurentRDC
